WIP: Database upgrades
ferrumc-rs/ferrumc pull request #136
Opened 2024-12-02 04:14 UTC by ReCore-sys

This PR provides many changes to the database system, primarily removing the multiple database options and using only LMDB. We've had great success with this database before and multiple databases has gotten very difficult to manage.

## Description

## Motivation and Context

## How has this been tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (restructuring code, without changing its behavior)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] Clippy passes with no warnings.

2024-12-08 01:30 UTC, 0xnim requested changes
Just these changes. And that question

2024-12-08 01:34 UTC, ReCore-sys commented on src/lib/adapters/anvil/src/lib.rs
> +    // Memory mapping is inherently unsafe since it's basically telling the os to use the file as,
On windows at least I wasn't able tot delete the database files while the server was running, but I'm not if that applies to other OSs

2024-12-08 04:51 UTC, merged

2024-12-08 05:07 UTC, 0xnim commented
Yeah its good

2024-12-29 04:10 UTC, vortexreanimated commented
can i just fucking ask who we is??
> We've had great success with this database before and multiple databases has gotten very difficult to manage.

2024-12-29 04:24 UTC, ReCore-sys commented
> can i just fucking ask who we is??
> 
> > We've had great success with this database before and multiple databases has gotten very difficult to manage.

First off, chill.
Secondly, we have tried a few databases in the past and LMDB is the only one that hasn't given us more headaches than it's worth. It's fast, uses minimal memory and doesn't have any weird caveats so it's a pretty good choice.

2024-12-29 05:14 UTC, Sweattypalms commented
@vortexreanimated lmaooo "we" as in the people who worked for ferrumc, duh?

LMDB worked pretty good last time: it has low memory usage, and has good access/write speeds. 
Although if we see better options, we would most likely change our db then.