feat: Inventories
ferrumc-rs/ferrumc pull request #151
Opened 2024-12-31 17:12 UTC by Outspending

Adds Inventories into Ferrumc.

- [x] Simple Inventory Implementation
- [ ] Inventory Content Manager (Setting rows / columns / ect)
- [x] Inventory Syncing (Viewers System?)
- [ ] Inventory Types such as AnvilInventory, CraftingInventory, BeaconInventory, ect...
- [x] Better Inventory Packets (Instead of sending a packet per slot)
- [x] Make it compatible with ECS
- [x] Inventory Clicking
- [ ] Player Inventory Support
- [ ] Creative Inventory Support
- [ ] Slot Structure

2025-01-04 04:54 UTC, 0xnim commented on src/lib/inventory/src/contents.rs
> +    pub size: usize,
does this need to be a usize?

2025-01-04 14:38 UTC, Outspending commented on src/lib/inventory/src/contents.rs
> +    pub size: usize,
no, it doesn't need to be usize. Do you want me to change it to something else?

2025-01-05 05:29 UTC, 0xnim commented on src/lib/inventory/src/contents.rs
> +    pub size: usize,
unless it has something to do with indexing which the cpu does better on native 64 bit or 32 bit. always define it. here a u32 or even a u16 should suffice i think

2025-01-05 05:32 UTC, Outspending commented on src/lib/inventory/src/contents.rs
> +    pub size: usize,
Yep I changed all the types to mostly u16 now, we chillin

2025-01-05 05:34 UTC, Sweattypalms commented on src/lib/inventory/src/contents.rs
> +    pub size: usize,
technically speaking, you shouldn't need more than `u8`, if you're changing anyways. 255 is more than enough innit?

2025-01-05 06:16 UTC, Outspending commented on src/lib/inventory/src/contents.rs
> +    pub size: usize,
Yeah, that's true. I prob should change it to a u8

2025-01-05 09:04 UTC, GStudiosX2 requested changes

2025-01-05 09:04 UTC, GStudiosX2 commented on src/bin/src/packet_handlers/login_process.rs
> -    broadcast_spawn_entity_packet(entity_id, &state).await?;
This needs to be added back

2025-01-05 09:04 UTC, GStudiosX2 commented on src/bin/src/packet_handlers/login_process.rs
> -async fn player_info_update_packets(entity_id: Entity, state: &GlobalState) -> NetResult<()> {
Same with this function

2025-01-05 09:04 UTC, GStudiosX2 commented on src/bin/src/packet_handlers/login_process.rs
> -async fn broadcast_spawn_entity_packet(entity_id: Entity, state: &GlobalState) -> NetResult<()> {
This too

2025-04-26 22:13 UTC, connor33341 reviewed
good code quality

2025-08-12 08:55 UTC, closed without merging