feature/see-other-players
ferrumc-rs/ferrumc pull request #152
Opened 2024-12-31 22:16 UTC by Sweattypalms

You can see other players move, you can crouch and uncrouch (metadata). If you leave it actually leaves.

## Description

Made it so players can see each other:
+Player Actions (Player Commands)
+Transform Event handler for seeing entities move
+Player Leave
+NetAngle
+Entity Metadata
+Head Rotation
+Spawn Entity
+Teleport Entity

Fixed broadcast
Remove entity on leave

## Motivation and Context

Doesn't solve shit. Just creates more problems.

## How has this been tested?

prayer to the god

## Screenshots (if appropriate):
i dont think you can put image in text like this maybe at a later time

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (restructuring code, without changing its behavior)

## Checklist:

- [ x ] My code follows the code style of this project.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] Clippy passes with no warnings.

2024-12-31 22:25 UTC, Sweattypalms commented
shit actually works for once

2024-12-31 22:27 UTC, Sweattypalms commented
can someone review the code please @ReCore-sys

2024-12-31 22:52 UTC, GStudiosX2 requested changes
Nice but a few changes

2024-12-31 22:52 UTC, GStudiosX2 commented on src/bin/src/packet_handlers/login_process.rs
> +            BroadcastOptions::default().except([entity_id]),
I'm pretty sure this needs to be sent to the joining player too

2024-12-31 22:52 UTC, GStudiosX2 commented on src/bin/src/packet_handlers/login_process.rs
> +    broadcast(&packet, state, BroadcastOptions::default()).await?;
I'm pretty sure this shouldn't be sent to the joining player

2025-01-01 05:43 UTC, ReCore-sys reviewed
Mostly fine, just a couple nitpicks

2025-01-01 05:43 UTC, ReCore-sys commented on src/lib/net/src/packets/outgoing/entity_metadata.rs
> +mod value {
Could we have some docs for this? Makes absolutely no sense at face value.

2025-01-01 05:43 UTC, ReCore-sys commented on src/lib/net/src/packets/outgoing/entity_metadata.rs
> +            let val = match self {
This seems kinda stupid. Idk if there are better options though.

2025-01-01 05:43 UTC, ReCore-sys commented on src/bin/src/packet_handlers/login_process.rs
> +        let mut writer = state.universe.get_mut::<StreamWriter>(entity_id)?;
Would be better to scope the streamwriter lock so it gets freed once the packets are done sending. Also what's the commented numbers for?

2025-01-01 11:29 UTC, Sweattypalms commented on src/lib/net/src/packets/outgoing/entity_metadata.rs
> +            let val = match self {
If it's stupid and it works, then it is not stupid.

2025-01-01 11:30 UTC, Sweattypalms commented on src/lib/net/src/packets/outgoing/entity_metadata.rs
> +            let val = match self {
Unless you want me to use unsafe code with casting in memory, I don't think there is any other way to do this

2025-01-01 11:32 UTC, Sweattypalms commented on src/bin/src/packet_handlers/login_process.rs
> +        let mut writer = state.universe.get_mut::<StreamWriter>(entity_id)?;
StreamWriter is already scoped, kindof. Gets dropped before `player_info_update_packets` and `broadcast_spawn_entity_packet`. Also I don't know what those numbers are either. I didn't add them, check git blame.

2025-01-01 11:47 UTC, ReCore-sys commented on src/lib/net/src/packets/outgoing/entity_metadata.rs
> +            let val = match self {
Nah if that's that best we can do that's fine

2025-01-01 11:48 UTC, ReCore-sys commented on src/bin/src/packet_handlers/login_process.rs
> +        let mut writer = state.universe.get_mut::<StreamWriter>(entity_id)?;
It's not dropped before the send keepalive thing. Its also not dropped before grabbing the chunk sender, which can cause deadlocks if we aren't careful

2025-01-01 11:48 UTC, Sweattypalms commented on src/bin/src/packet_handlers/login_process.rs
> +            BroadcastOptions::default().except([entity_id]),
This is not that packet for TabList. This is for `AddPlayer`, and I tried sending to the joining player and I couldn't move after joining.

2025-01-01 17:51 UTC, merged

2025-01-01 23:22 UTC, GStudiosX2 commented on src/bin/src/packet_handlers/login_process.rs
> +            BroadcastOptions::default().except([entity_id]),
> This is not that packet for TabList. This is for `AddPlayer`, and I tried sending to the joining player and I couldn't move after joining.

Player info update still need to be sent to the joining player if you want skins (well we need auth first anyway)?

Also for the spawn entity it shouldn't be sent for the joining player I'm pretty sure your doing that right now no?