Implement RSA encryption (with update for current rewrite structure)
ferrumc-rs/ferrumc pull request #56
Opened 2024-09-18 20:14 UTC by en1gma713

The same as my last PR but it works this time and is up-to-date on the file structure

2024-09-18 20:37 UTC, Asurar0 commented on src/lib/net/encryption/src/key.rs
> +    pub private_key: RsaPrivateKey, //private key side of the keypair (for decryption)
When documenting field the actual syntax should be:
```rust
/// public key side of the keypair (for encryption)
pub public_key: RsaPublicKey
```
As it ties the documentation comment to the field that is then viewable with Rust-analyzer/LSP

2024-09-18 20:40 UTC, Asurar0 requested changes

2024-09-18 20:40 UTC, Asurar0 commented on src/lib/net/encryption/Cargo.toml
> +rand = "0.8.5"
These dependencies should be placed in the workspace (project root) `Cargo.toml` and then imported as 
`crate = { workspace = true }`

See https://github.com/ferrumc-rs/ferrumc/blob/rewrite/v3/src/lib/README.MD

2024-09-18 21:53 UTC, en1gma713 commented
fixed it

2024-09-19 16:45 UTC, en1gma713 commented
facing version conflicts between rand and rand_core now

2024-10-10 04:42 UTC, ReCore-sys commented
@en1gma713 we've added the networking stack now, if you'd be able to sort out the conflicts and make sure all of your stuff works ok with the new code, im happy to merge

2024-11-27 04:33 UTC, ReCore-sys commented
No work is being done one this and the codebase has evolved to the point where this PR is unlikely to be easier to fix than just writing from scratch again

2024-11-27 04:33 UTC, closed without merging